export const FETCH_BANK_DATA = 'FETCH_BANK_DATA';
export const FETCH_BANK_SUCCESS = 'FETCH_BANK_SUCCESS';
export const FETCH_BANK_FAIL = 'FETCH_BANK_FAIL';
export const ADD_BANK_DATA = 'ADD_BANK_DATA';
export const FETCH_BANK_DETAILS = 'FETCH_BANK_DETAILS';
export const UPDATE_BANK = 'UPDATE_BANK';
export const DELETE_BANK = 'DELETE_BANK';

// Bank transaction list
export const FETCH_BANK_TRANSACTION_DATA = 'FETCH_BANK_TRANSACTION_DATA';
export const ADD_BANK_TRANSACTION_DATA = 'ADD_BANK_TRANSACTION_DATA';
export const FETCH_BANK_TRANSACTION_DETAILS = 'FETCH_BANK_TRANSACTION_DETAILS';
export const UPDATE_BANK_TRANSACTION_DATA = 'UPDATE_BANK_TRANSACTION_DATA';