// Card type set up ------ action type
export const FETCH_CARDTYPE_SETUP_DATA = "FETCH_CARDTYPE_SETUP_DATA";
export const FETCH_PRODUCT_FAIL = "FETCH_PRODUCT_FAIL";
export const ADD_CARDTYPE_SETUP_DATA = "ADD_CARDTYPE_SETUP_DATA";
export const FETCH_CARDTYPE_SETUP_DETAILS = "FETCH_CARDTYPE_SETUP_DETAILS";
export const DELETE_CARDTYPE_SETUP = "DELETE_CARDTYPE_SETUP";
export const UPDATE_CARDTYPE_SETUP_DATA = "UPDATE_CARDTYPE_SETUP_DATA";

// Card type ---- action type
export const FETCH_CARDTYPE_DATA = "FETCH_CARDTYPE_DATA";
export const ADD_CARDTYPE_DATA = "ADD_CARDTYPE_DATA";
export const FETCH_CARDTYPE_DETAILS = "FETCH_CARDTYPE_DETAILS";
export const UPDATE_CARDTYPE_DETAIL = "UPDATE_CARDTYPE_DETAIL";
