export const ADD_CASHCOLLECTION_DATA = 'ADD_CASHCOLLECTION_DATA';
export const FETCH_CASHCOLLECTION_SUCCESS = 'FETCH_CASHCOLLECTION_SUCCESS';
export const FETCH_CASHCOLLECTION_FAIL = 'FETCH_CASHCOLLECTION_FAIL';
export const UPDATE_CASH_COLLECTION = 'UPDATE_CASH_COLLECTION';