export const ADD_CASHDELIVERY_DATA = 'ADD_CASHDELIVERY_DATA';
export const FETCH_CASHDELIVERY_SUCCESS = 'FETCH_CASHDELIVERY_SUCCESS';
export const FETCH_CASHDELIVERY_FAIL = 'FETCH_CASHDELIVERY_FAIL';
export const UPDATE_CASHDELIVERY = 'UPDATE_CASHDELIVERY';