
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS'
export const ADD_CATEGORY_DATA = 'ADD_CATEGORY_DATA'
export const FETCH_CATEGORY_DETAILS = 'FETCH_CATEGORY_DETAILS'
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY'
export const DELETE_CATEGORY = 'DELETE_CATEGORY'