export const FETCH_CREDIT_SALES = "FETCH_CREDIT_SALES";
export const FETCH_CREDIT_SALES_DETAILS = "FETCH_CREDIT_SALES_DETAILS";
export const UPDATE_CREDIT_SALES = "UPDATE_CREDIT_SALES";
export const UPDATE_INTEREST_AMOUNT = "UPDATE_INTEREST_AMOUNT";
export const ADD_CREDITSALES_DATA = "ADD_CREDITSALES_DATA";
export const ADD_ORDER_FAIL = "ADD_ORDER_FAIL";
export const FETCH_CREDIT_SALES_CUSTOMER = "FETCH_CREDIT_SALES_CUSTOMER";
