export const FETCH_DAMAGED_DATA = 'FETCH_DAMAGED_DATA';
export const ADD_DAMAGED_DATA = 'ADD_DAMAGED_DATA';
export const UPDATE_DAMAGE_PRODUCT = 'UPDATE_DAMAGE_PRODUCT';
export const DELETE_DAMAGE_PRODUCT = 'DELETE_DAMAGE_PRODUCT';

 