export const FETCH_DESIGNATION_DATA = 'FETCH_DESIGNATION_DATA';
export const ADD_DESIGNATION_DATA = 'ADD_DESIGNATION_DATA';
export const ADD_DESIGNATION_FAIL = 'ADD_DESIGNATION_FAIL';
export const FETCH_DESIGNATION_DETAILS = 'FETCH_DESIGNATION_DETAILS';
export const UPDATE_DESIGNATION = 'UPDATE_DESIGNATION';
export const DELETE_DESIGNATION = 'DELETE_DESIGNATION';