export const FETCH_EMPLOYEE_DATA = 'FETCH_EMPLOYEE_DATA';
export const ADD_EMPLOYEE_DATA = 'ADD_EMPLOYEE_DATA';
export const ADD_EMPLOYEE_FAIL = 'ADD_EMPLOYEE_FAIL';  
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';