export const FETCH_EXPENDUTURE_DATA = "FETCH_EXPENDUTURE_DATA";
export const ADD_EXPENDUTURE_DATA = "ADD_EXPENDUTURE_DATA";
export const UPDATE_EXPENDUTURE = "UPDATE_EXPENDUTURE";
export const DELETE_EXPENDUTURE_DATA = "DELETE_EXPENDUTURE_DATA";