export const FETCH_EXPENSE_INCOME_DATA = "FETCH_EXPENSE_INCOME_DATA";
export const ADD_EXPENSE_INCOME_DATA = "ADD_EXPENSE_INCOME_DATA";
export const UPDATE_EXPANSE_INCOME = "UPDATE_EXPANSE_INCOME";
export const DELETE_EXPENSE_INCOME_DATA = "DELETE_EXPENSE_INCOME_DATA";
