// Product actions type
export const FETCH_PRODUCT_REQUEST = "FETCH_PRODUCT_REQUEST";
export const FETCH_PRODUCT_DATA = "FETCH_PRODUCT_DATA";
export const UPDATE_PRODUCT_DATA = "UPDATE_PRODUCT_DATA";
export const FETCH_PRODUCT_FAIL = "FETCH_PRODUCT_FAIL";
export const ADD_PRODUCT_DATA = "ADD_PRODUCT_DATA";
export const FETCH_PURCHASE_PRODUCT_DATA = "FETCH_PURCHASE_PRODUCT_DATA";
export const FETCH_SALES_PRODUCT_DATA = "FETCH_SALES_PRODUCT_DATA";
export const FETCH_PROUDCT_LIST = "FETCH_PROUDCT_LIST";
export const FETCH_PRODUCT_DATA_WITH_QR_BAR_CODE =
  "FETCH_PRODUCT_DATA_WITH_QR_BAR_CODE";

// Color actions type
export const FETCH_COLOR_DATA = "FETCH_COLOR_DATA";
export const ADD_COLOR_DATA = "ADD_COLOR_DATA";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const FETCH_PRODUCT_SHORTAGE = "FETCH_PRODUCT_SHORTAGE";
