//Purchase order types
export const FETCH_PURCHASE_ORDER_DATA = 'FETCH_PURCHASE_ORDER_DATA';
export const ADD_PURCHASE_ORDER_DATA = 'ADD_PURCHASE_ORDER_DATA';
export const ADD_PURCHASE_ORDER_FAIL = 'ADD_PURCHASE_ORDER_FAIL';
export const UPDATE_PURCHASE_ORDER_DATA = 'UPDATE_PURCHASE_ORDER_DATA';
export const DELETE_PURCHASE_ORDER = 'DELETE_PURCHASE_ORDER';


//Purchase stock types
export const FETCH_PURCHASE_STOCK_DATA = 'FETCH_PURCHASE_STOCK_DATA';
export const ADD_PURCHASE_STOCK_DATA = 'ADD_PURCHASE_STOCK_DATA';
 