//Purchase return types
export const FETCH_PURCHASE_RETURN_DATA = 'FETCH_PURCHASE_RETURN_DATA';
export const ADD_PURCHASE_RETURN_DATA = 'ADD_PURCHASE_RETURN_DATA';
export const ADD_PURCHASE_RETURN_FAIL = 'ADD_PURCHASE_RETURN_FAIL';
export const UPDATE_PURCHASE_RETURN = 'UPDATE_PURCHASE_RETURN';

