export const FETCH_DAILY_SALES = "FETCH_DAILY_SALES";
export const FETCH_MONTHLY_SALES = "FETCH_MONTHLY_SALES";
export const FETCH_YEARLY_SALES = "FETCH_YEARLY_SALES";

export const FETCH_DAILY_PURCHASE = "FETCH_DAILY_PURCHASE";
export const FETCH_MONTHLY_PURCHASE = "FETCH_MONTHLY_PURCHASE";
export const FETCH_YEARLY_PURCHASE = "FETCH_YEARLY_PURCHASE";

export const FETCH_EXPENDITURE_REPORTS = "FETCH_EXPENDITURE_REPORTS";
export const FETCH_AVAILABLE_STOCK = "FETCH_AVAILABLE_STOCK";
export const FETCH_SUPPLIER_WISE_PURCHASE = "FETCH_SUPPLIER_WISE_PURCHASE";
export const FETCH_SUMMARY_REPORTS = "FETCH_SUMMARY_REPORTS";

export const FETCH_CUSTOMER_WISE_SALES = "FETCH_CUSTOMER_WISE_SALES";
export const FETCH_SUPPLIER_DUE = "FETCH_SUPPLIER_DUE";
export const FETCH_CUSTOMER_DUE = "FETCH_CUSTOMER_DUE";
export const FETCH_SUPPLIER_LEDGER = "FETCH_SUPPLIER_LEDGER";
export const FETCH_DAMAGE_PRODUCTS = "FETCH_DAMAGE_PRODUCTS";
export const FETCH_CASH_RECEIVE_AND_DELIVERY_REPORT =
  "FETCH_CASH_RECEIVE_AND_DELIVERY_REPORT";
export const FETCH_PRODUCT_SALE_PUR = "FETCH_PRODUCT_SALE_PUR";
export const FETCH_COMPANY_BENEFIT_BY_PRODUCT =
  "FETCH_COMPANY_BENEFIT_BY_PRODUCT";
export const FETCH_CUSTOMER_RETURN = "FETCH_CUSTOMER_RETURN";
export const FETCH_CUSTOMER_LEDGER = "FETCH_CUSTOMER_LEDGER";
export const FETCH_UPCOMMING_INSTALLMENT = "FETCH_UPCOMMING_INSTALLMENT";
export const FETCH_INSTALLMENT_COLLECTION = "FETCH_INSTALLMENT_COLLECTION";
export const FETCH_DEFAULTING_CUSTOMER = "FETCH_DEFAULTING_CUSTOMER";
export const FETCH_BANK_LEDGER = "FETCH_BANK_LEDGER";
export const FETCH_CUSTOMER_BENEFIT = "FETCH_CUSTOMER_BENEFIT";
export const FETCH_CASH_IN_HAND = "FETCH_CASH_IN_HAND";
export const FETCH_PROFIT_LOSS = "FETCH_PROFIT_LOSS";
