//Purchase return types
export const FETCH_SALES_RETURN_DATA = 'FETCH_SALES_RETURN_DATA';
export const ADD_SALES_RETURN_DATA = 'ADD_SALES_RETURN_DATA';
export const ADD_SALES_RETURN_FAIL = 'ADD_SALES_RETURN_FAIL';
export const UPDATE_SALES_RETURN = 'UPDATE_SALES_RETURN';

