export const FETCH_ORDER_DATA = "FETCH_ORDER_DATA";
export const FETCH_SALES_ORDER_DETAILS = "FETCH_SALES_ORDER_DETAILS";
export const ADD_ORDER_DATA = "ADD_ORDER_DATA";
export const ADD_ORDER_FAIL = "ADD_ORDER_FAIL";
export const DELETE_ORDER = "DELETE_ORDER";
export const SALES_RECEIPT = "SALES_RECEIPT";
export const SALES_PRODUCT_DETAILS = "SALES_PRODUCT_DETAILS";
