// Share investment head
export const FETCH_SHARE_INVESTMENT_HEAD = 'FETCH_SHARE_INVESTMENT_HEAD'
export const ADD_SHARE_INVESTMENT_HEAD = 'ADD_SHARE_INVESTMENT_HEAD'

// Share investment
export const FETCH_SHARE_INVESTMENT_DATA = 'FETCH_SHARE_INVESTMENT_DATA'