export const FETCH_SUPPLIER_REQUEST = "FETCH_SUPPLIER_REQUEST";
export const FETCH_SUPPLIER_DATA = "FETCH_SUPPLIER_DATA";
export const FETCH_SUPPLIER_FAIL = "FETCH_SUPPLIER_FAIL";
export const ADD_SUPPLIER_DATA = "ADD_SUPPLIER_DATA";
export const DELETE_SUPPLIER_DATA = "DELETE_SUPPLIER_DATA";
export const UPDATE_SUPPLIER_DATA = "UPDATE_SUPPLIER_DATA";
