export const StockData = [

{
    id: "1",
    stockCode: "1001",
    productName: "Asus Laptop",
    category: "Laptop",
    company: "Asus",
    otv: "1",
    purchaseRate: "123.54",
    mrp: "400",
    totalPrice: "250",
},
{
    id: "2",
    stockCode: "1002",
    productName: "Asus Laptop",
    category: "Laptop",
    company: "Asus",
    otv: "1",
    purchaseRate: "123.54",
    mrp: "400",
    totalPrice: "250",
},
{
    id: "3",
    stockCode: "1003",
    productName: "Asus Laptop",
    category: "Laptop",
    company: "Asus",
    otv: "1",
    purchaseRate: "123.54",
    mrp: "400",
    totalPrice: "250",
},
{
    id: "4",
    stockCode: "1004",
    productName: "Asus Laptop",
    category: "Laptop",
    company: "Asus",
    otv: "1",
    purchaseRate: "123.54",
    mrp: "400",
    totalPrice: "250",
},
{
    id: "5",
    stockCode: "1005",
    productName: "Asus Laptop",
    category: "Laptop",
    company: "Asus",
    otv: "1",
    purchaseRate: "123.54",
    mrp: "400",
    totalPrice: "250",
},
{
    id: "6",
    stockCode: "1006",
    productName: "Asus Laptop",
    category: "Laptop",
    company: "Asus",
    otv: "1",
    purchaseRate: "123.54",
    mrp: "400",
    totalPrice: "250",
},
{
    id: "7",
    stockCode: "1007",
    productName: "Asus Laptop",
    category: "Laptop",
    company: "Asus",
    otv: "1",
    purchaseRate: "123.54",
    mrp: "400",
    totalPrice: "250",
},
{
    id: "8",
    stockCode: "1008",
    productName: "Asus Laptop",
    category: "Laptop",
    company: "Asus",
    otv: "1",
    purchaseRate: "123.54",
    mrp: "400",
    totalPrice: "250",
},
{
    id: "9",
    stockCode: "1009",
    productName: "Asus Laptop",
    category: "Laptop",
    company: "Asus",
    otv: "1",
    purchaseRate: "123.54",
    mrp: "400",
    totalPrice: "250",
},
{
    id: "10",
    stockCode: "1010",
    productName: "Asus Laptop",
    category: "Laptop",
    company: "Asus",
    otv: "1",
    purchaseRate: "123.54",
    mrp: "400",
    totalPrice: "250",
},
{
    id: "11",
    stockCode: "1011",
    productName: "Asus Laptop",
    category: "Laptop",
    company: "Asus",
    otv: "1",
    purchaseRate: "123.54",
    mrp: "400",
    totalPrice: "250",
},
{
    id: "12",
    stockCode: "1012",
    productName: "Asus Laptop",
    category: "Laptop",
    company: "Asus",
    otv: "1",
    purchaseRate: "123.54",
    mrp: "400",
    totalPrice: "250",
},
{
    id: "13",
    stockCode: "1013",
    productName: "Asus Laptop",
    category: "Laptop",
    company: "Asus",
    otv: "1",
    purchaseRate: "123.54",
    mrp: "400",
    totalPrice: "250",
},
{
    id: "14",
    stockCode: "1014",
    productName: "Asus Laptop",
    category: "Laptop",
    company: "Asus",
    otv: "1",
    purchaseRate: "123.54",
    mrp: "400",
    totalPrice: "250",
},
{
    id: "15",
    stockCode: "1015",
    productName: "Asus Laptop",
    category: "Laptop",
    company: "Asus",
    otv: "1",
    purchaseRate: "123.54",
    mrp: "400",
    totalPrice: "250",
},
{
    id: "16",
    stockCode: "1016",
    productName: "Asus Laptop",
    category: "Laptop",
    company: "Asus",
    otv: "1",
    purchaseRate: "123.54",
    mrp: "400",
    totalPrice: "250",
},
 

];